---
sudo: required
dist: bionic
language: java

before_install:
  - sudo apt update
  - sudo apt install software-properties-common
  - sudo apt-add-repository --yes --update ppa:ansible/ansible
  - sudo apt install ansible

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - echo ${SSH_PRIVATE_KEY} | base64 --decode > ansible/mykey
  - chmod 600 ansible/mykey
  - pushd ansible && ansible-playbook service.yaml
  - popd && rm ansible/mykey
