---
services:
  - docker

before_install:
  - 'sudo docker pull maven:latest'
  - 'sudo docker pull williamyeh/ansible:ubuntu18.04'

script:
  - docker run -it -v $(pwd):/tmp maven bash -c " cd /tmp && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
  - docker run -it -v $(pwd):/tmp williamyeh/ansible:ubuntu18.04 bash -c " cd /tmp/spring-petclinic-rest/ansible && ansible-playbook backend_service.yaml -v"
