- hosts: backend_service
  remote_user: root
  gather_facts: false
  vars_files:
    - values.yaml
  tasks:
    - name: Build jar file for rest service
      shell: |
        cd /tmp/spring-petclinic-rest
        mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - block:
      - name: Create service file
        template:
          src: /tmp/spring-petclinic-rest/ansible/templates/backend_service.j2
          dest: /etc/systemd/system/petclinic-rest.service
          mode: 0644

      - name: Start service
        systemd:
          name: petclinic-rest
          state: restarted
          enabled: yes

      become: yes
      become_user: root
