- hosts: backend_service
  remote_user: root
  gather_facts: false
  vars_files:
    - values.yaml
  vars:
    remote_path: /home/ubuntu/spring-petclinic-rest/target
    local_ansible_path: /tmp/spring-petclinic-rest
  tasks:
    - block:
      - name: Make sure destination dir exists
        file:
          path: "{{remote_path}}"
          state: directory
          recurse: yes
      - name: Copy jar file to bin directory
        copy:
          src: "{{local_ansible_path}}/target/spring-petclinic-rest-{{service_version}}.jar"
          dest: "{{remote_path}}/spring-petclinic-rest-{{service_version}}.jar"
      - name: Create service file
        template:
          src: "{{local_ansible_path}}/ansible/templates/backend_service.j2"
          dest: /etc/systemd/system/petclinic-rest.service
          mode: 0644

      - name: Start service
        systemd:
          name: petclinic-rest
          state: restarted
          enabled: yes

      become: yes
      become_user: root
